alter table RDAP_DOMAIN  add column CUSTOM_PROPERTIES  MEDIUMTEXT;
alter table RDAP_NAMESERVER  add column CUSTOM_PROPERTIES  MEDIUMTEXT;
alter table RDAP_IP  add column CUSTOM_PROPERTIES  MEDIUMTEXT;
alter table RDAP_ENTITY  add column CUSTOM_PROPERTIES  MEDIUMTEXT;
alter table RDAP_AUTNUM  add column CUSTOM_PROPERTIES  MEDIUMTEXT;